# Generated by Django 2.2 on 2021-12-11 10:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('article_name', models.CharField(max_length=100, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('article_title', models.CharField(blank=True, max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='article')),
                ('ticket_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('F', 'forex'), ('C', 'commodities'), ('G', 'guest_post')], max_length=1)),
            ],
        ),
    ]
